### ISSUE TITLE
Using this calendar to display available/booked information.

### ISSUE THREAD

**Issue by khdhhde21** [uvarov-frontend/vanilla-calendar-pro#158]
Hi. How difficult is to customize this calendar to a simple use case of displaying availability of a rental boat? For a given date, the boat is either available or booked (not available). All booking happens over the phone, so the calendar is read-only. The date picker function should be disabled. There's no need to indicate whether a day is a holiday. By default, all dates are 'available' and there should be a way to set the already booked dates during the calendar initialization. There should be a way to style the Available and the Booked cell text color and background color.

Can vanilla-calendar-pro handle this out of the box, or would it require changing TypeScript and re-building it? 

Thanks in advance.

**Comment by uvarov-frontend** [comment]
Everything you described is available out of the box.

**Comment by uvarov-frontend** [comment]
To turn off date selection:
```
settings: {
  selection: {
    day: false,
  },
}
```
This is described in the documentation https://vanilla-calendar.pro/docs/reference/additionally/settings#selection-day

I think it would be logical to make the reserved dates "disabled" so that they indicate that the dates are occupied.

To disable dates:
```
settings: {
  range: {
    disabled: ['2022-08-10:2022-08-15', '2022-08-20'],
  }
}
```
You need to style the disabled dates using CSS. (Disabled dates have the modifier `dayBtnDisabled`).

**Comment by khdhhde21** [comment]
Thank you for your quick responses! The calendar works as described.
