### ISSUE TITLE
Range:min not working

### ISSUE THREAD

**Issue by thisismeonmounteverest** [uvarov-frontend/vanilla-calendar-pro#183]
The example given in the doc doesn't allow to select anything earlier than 1970-01-01 but should allow to select dates back till 1920-01-01: https://vanilla-calendar.pro/docs/learn/date-range/start-and-end-of-existing-dates

**Comment by whataboutpereira** [comment]
It's not actually range.min, but date.min, which is overriden by range.min.

**Comment by whataboutpereira** [comment]
It took me a while to understand, but if you're using date.min that is lower than the default range.min of 1970, you also need to set range.min. Perhaps this could be stressed in the docs?

**Comment by thisismeonmounteverest** [comment]
@whataboutpereira Thanks for the hint. 

But the example doesn't say anything about what you need to do and if you ask me that behavior looks conspicuously like a bug.

**Comment by uvarov-frontend** [comment]
`date.min` and `date.max` - indicates the maximum possible dates in the calendar. Use only when you know exactly the possible range of possible dates.
`range.min` and `range.max` - have similar behavior, but in fact they disable dates outside of them. You can enable `visibility.disabled` and then dates outside `range.min` and `range.max` will be visible but not selectable.

`range.min` must not contain a date less than `date.min`. With `max` parameters everything is similar.

Here is an example of a working setup:
```
const options: Options = {
  date: {
    min: '1920-01-01',
    max: '2038-12-31',
  },
  settings: {
    range: {
      min: '2000-01-01',
      max: '2024-12-31',
    },
    visibility: {
      disabled: true,
    },
  },
};
```
Here, the minimum possible year to display is 1920, and the maximum is 2038. All because `visibility.disabled` is enabled. If you disable it, you will see that the maximum and minimum year will be taken from `range.min` and `range.max`.

Please open the task again if something does not follow the logic I specified.
