### ISSUE TITLE
Arrows with pointer-events: auto receive clicks when calendar is hidden.

### ISSUE THREAD

**Issue by whataboutpereira** [uvarov-frontend/vanilla-calendar-pro#190]
https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/22724651/7aca5a9f-65f1-420f-9078-345ab2e30dc6

As can be seen from the video, the right arrow of the left calendar stops working when the right calendar is hidden. Initially I thought it's a z-index issue, but I see it's caused by arrows forcing pointer-events: auto. This overrides pointer-events: none from .vanilla-calendar_hidden. So in essence in this example the right hidden calendar is receiving click events and changing its month instead.

**Comment by uvarov-frontend** [comment]
I can't reproduce this issue, please create an example with the bug in codesandbox.io

**Comment by whataboutpereira** [comment]
https://codesandbox.io/p/sandbox/gifted-danilo-zdc833?file=%2Fcalendar.ts

- Click on left input
- Click on right input
- Click on left input
- Click on calendar right arrow

**Comment by uvarov-frontend** [comment]
I was able to see the problem, thanks! I'm figuring it out!

**Comment by uvarov-frontend** [comment]
The problem turned out to be completely ridiculous.
1. When you click on the left input, a calendar instance is created.
2. Clicking on the second input creates a second instance of the calendar.
3. Clicking the left input again displays the first calendar created, but when you try to click the right arrow, you are actually clicking the left arrow from the calendar for the right input.
![Screen-Shot-2024-02-18-12-47-41-1708249676](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/82662379/e3feeafa-f83a-494b-80b2-3ef444e22926)

This is because the arrows do not have `pointer-events: none` when the calendar is hidden. This is not correct behavior, I will fix it by adding to the css:
```
.vanilla-calendar_hidden * {
  pointer-events: none !important;
}
```
