### ISSUE TITLE
months: 1 not working

### ISSUE THREAD

**Issue by aur0** [uvarov-frontend/vanilla-calendar-pro#280]
months: 1 not working for me it just shows 2 months instead

0 2 3 4 5 etc all work but not 1

**Comment by uvarov-frontend** [comment]
Why are you using `type: 'multiple'` instead of `type: 'default'`? 
Obviously 'multiple' means displaying multiple months.
[The months parameter specifies the number of displayed months when the calendar type is set to 'multiple'.](https://vanilla-calendar.pro/docs/reference/main/main-settings#months)

**Comment by aur0** [comment]
My bad thanks
