### ISSUE TITLE
Improved popup trigger on tap on Android/Chromium

### ISSUE THREAD

**Issue by pl-mnm** [uvarov-frontend/vanilla-calendar-pro#287]
Tapping a date with a popup on Android only displays the popup for the length of the tap. A longer press does seem keep the popup open. A quick tap on iOS keeps the popup open straight away. I haven't found any docs about these respective behaviours.

Is it at all possible to improve this, so that a quick tap on Android keeps the popup open? We are not making use of the date picking functionalities, in that case would it be possible to trigger the popup in JS?

**Comment by uvarov-frontend** [comment]
Hello, at the moment the `popups` function only works when hovering over the date, which is why clicking on the date causes the `hover` event, this is not correct for mobile devices, I will add an option with which you can call `popups` by clicking on the date, but so far there is no such option, you can write your own the function of creating and displaying a pop-up by clicking on a date.

**Comment by uvarov-frontend** [comment]
Fixed in v3.0.0
