### ISSUE TITLE
regression in v3 between than beta.17 and beta.33: `/build` folder not part of npm package in v3.0.0-beta.33

### ISSUE THREAD

**Issue by johanrd** [uvarov-frontend/vanilla-calendar-pro#323]
npm install vanilla calendar pro 3.0.0-beta.33 and see that the built package folder `build` is not included:

| npm package in 3.0.0-beta.33  |
|---|
|<img width="409" alt="Screenshot 2024-11-06 at 09 25 04" src="https://github.com/user-attachments/assets/787c9de0-8f43-4c9f-84a3-04835e205c87">|

Expected from e.g. beta.17:
| npm package in 3.0.0-beta.17| 
|---|
|<img width="616" alt="Screenshot 2024-11-06 at 09 24 18" src="https://github.com/user-attachments/assets/6a646bc0-0d2c-4d35-9d0e-bed8b6be43aa">|

**Comment by johanrd** [comment]
or, maybe I'm fooling myself about the expected format.

Anyways, the instructions in the readme does not work in beta.33, at least. Then the following runtime errors occur:

```
import VanillaCalendar from 'vanilla-calendar-pro';
// TypeError: vanilla_calendar_pro__WEBPACK_IMPORTED_MODULE_5__.default is not a constructor

import 'vanilla-calendar-pro/styles/vanilla-calendar-pro.min.css';
// Error: Could not find module `vanilla-calendar-pro/styles/vanilla-calendar-pro.min.css` imported from `(require)`
```

**Comment by uvarov-frontend** [comment]
Please wait for the updated documentation, the old readme will work in the new version since critical changes have been made.

There is no build folder anymore, in beta.33 you export styles like this:
import 'vanilla-calendar-pro/styles/index.css';
And the calendar itself is like this: import { VanillaCalendarPro } from 'vanilla-calendar-pro';

Most likely, the import of the calendar in the next beta version will be replaced from VanillaCalendarPro to Calendar.

**Comment by johanrd** [comment]
great, thanks, verified!
