### ISSUE TITLE
Add `data-vc-date-selected` and `data-vc-date-hover` when `disableWeekdays` is active

### ISSUE THREAD

**Issue by afonic** [uvarov-frontend/vanilla-calendar-pro#329]
Hello! Congrats on releasing v3, this is probably the best vanilla datepicker in development!

I don't know if it's intentional or some regression but I've noticed that when I'm using `multiple-ranged` mode plus `disableWeekdays`, these data properties do not get applied on hover or after the selection. `data-vc-date-selected` does appear if I preset a range using `selectedDates`.

My use case is that I want to allow the user to select ranges only between each Saturday and Sunday. So I set `disableWeekdays: [1,2,3,4,5]` but since the styling does not get applied it's confusing since it displays like this:

<img width="428" alt="Screenshot 2024-11-08 at 1 58 58 PM" src="https://github.com/user-attachments/assets/f1a152ad-e154-4067-9c7a-45e265f7e783">

Even though I'm trying to select 16/11 to 24/11.

Is there a way to resolve this on my side ?

Thanks in advance!

**Comment by uvarov-frontend** [comment]
Hello, create an example of your problem in a sandbox, for example in codesandbox.io, I don’t quite understand what problem you are talking about.

**Comment by afonic** [comment]
Sure thing.

In this example: https://codesandbox.io/p/sandbox/modest-meninsky-fvjrgh

I want the selection to display like this, even though the dates are disabled:

<img width="532" alt="Screenshot 2024-11-08 at 4 55 34 PM" src="https://github.com/user-attachments/assets/d4afe057-f308-4faa-a46e-fdc7516ef810">

Right now if you select those dates it appears like my screenshot before and it's confusing to the user. 

This is an example of what I'm trying to recreate: https://archonyachting.com/ (different calendar)

**Comment by ghiscoding** [comment]
So you still want to see the background color on the date range even over the disabled week days when selecting the dates (perhaps with a lighter gray because they are disabled), is that what you want to do when selecting the dates? What about when you release the mouse though? ... in simpler words, you want `data-vc-date-selected="middle"` attribute to also be added to the disabled ones

![image](https://github.com/user-attachments/assets/ef5b7d19-5310-45e1-9165-771888046d62)

**Comment by afonic** [comment]
Hello,

Yes it will, but it more appropriately displays what the user has selected in some cases. For example, `disableWeekdays` might mean that these days are unavailable but it might also mean that they are unavailable as the start or end date of a date range.

From my understanding, that's why the `enableEdgeDatesOnly` settings exists, otherwise this date range should not be selectable at all.

So there are two cases: (when using `multiple-ranged`)

- You only want to allow specific start / end dates for a date range but the selected range includes the whole week. That's what I'm trying to do using `disableWeekdays: [1,2,3,4,5]` and `enableEdgeDatesOnly: true`. This works, but it's displayed to the user wrong in the calendar.
- You only want to allow the user to select the enabled date. You can set `enableEdgeDatesOnly: false` and it appears correctly.

I will send a PR for the first one and you can decide if that's something you want to include or not.

**Comment by ghiscoding** [comment]
Just to be clear, I'm the one who added the `enableEdgeDatesOnly` option and the reason I created this option is because in a data grid (my project) I'm only interested in the start & end dates to return data between these 2 dates and I don't care about the middle dates (in other words, I don't care about the dates in between and I don't disable any of them either). The end result of the edge is that the `selectedDates` will be an array of 2 dates instead of being an array of `n` where `n` is all the dates you selected including the middle dates and so the edge is giving a much simpler array of 2 items only.

I'm not sure that this edge option will play nice with other options like what you're trying to do here, it wasn't designed to do that, or at least it wasn't in my mind when I added the option. You can see the PR #275 where I added the edge option and it also shows how it works with print screens. I did also add a note on the edge option that could be of concern

> It's important to note that with this setting, disabling dates within the date range will have no effect. So make sure to use this parameter when you are interested with only the start and end date but nothing in-between.

**Comment by afonic** [comment]
Yeah that's why I noted in the PR that maybe this needs another config option to work correctly. Thanks for adding the option! 

Since it's `true` by default in v3, it creates the scenario that I described, that the user selects a date range (so we just get the start and end date - correct) but in the calendar it seems like he selected 4 days (instead of the whole range).

**Comment by ghiscoding** [comment]
> Since it's `true` by default in v3

ah I didn't noticed the default changed, that's good to know

**Comment by uvarov-frontend** [comment]
I didn’t have time to consider your question yesterday, but I saw that you even created a PR. 🙂
Your problem is that you think of disabling dates as simply a visualization for the user, but it's not. The bottom line is that if a date is disabled, then it cannot be selected, in any way, except by specifying it via `selectedDates`, although I would remove this too, but I think it would be too strict on my part for other calendar users, I left this up to the developers, as long as they know what they're doing.

As for your question, it can be solved in a few lines of code, without having to do a PR.

```ts
const calendar = new Calendar('#calendar', {
  type: 'multiple',
  selectionDatesMode: 'multiple-ranged',
  // disableWeekdays: [1, 2, 3, 4, 5],
  onCreateDateEls(self, dateEl) {
    if (![1, 2, 3, 4, 5].includes(Number(dateEl.dataset.vcDateWeekDay))) return;
    (dateEl.firstChild as HTMLElement).onclick = (event) => event.stopPropagation();
    (dateEl.firstChild as HTMLElement).style.cssText = 'cursor: default; opacity: 0.5;';
  },
});
calendar.init();
```
And please note `enableEdgeDatesOnly` has nothing to do with it at all. In the new version I made enableEdgeDatesOnly enabled by default as it is more performant for the default calendar. I reported this here: [#319](https://github.com/uvarov-frontend/vanilla-calendar-pro/issues/319#issuecomment-2452999348)

Here's an example in a sandbox: https://codesandbox.io/p/sandbox/modest-meninsky-fvjrgh

**Comment by afonic** [comment]
Thank you, this works very well!

I'd argue that if a day isn't meant to be selected then any range containing a disabledDate shouldn't be selectable at all, but you know how it's built better than me.

Thanks again!
